### ISSUE TITLE
Getting start (and end) addresses of a GeoLayout for binary export

### ISSUE THREAD

**Issue by KoopintheHub** [Fast-64/fast64#210]
I know binary exporting is an abandoned thing but it's pretty useful to me
I've been trying to find the koopa's (with a shell) geolayout's start (and end) address for binary exporting.
I've got the model object and the level script address but I;ve been trying to get the start addresses but it just says the address is not provided in any of the segments.

Is there a way how to do this?

**Comment by jesusyoshi54** [comment]
This doesn't really have much to do with fast64 itself.
If it is an issue with finding a segment, maybe you should try selecting a different level for the import. Make sure you select a level that actually uses the model you're importing. That said though you could also just have the wrong address.
I have written some sm64 tutorials on how to find binary data addresses that you can reference on my personal site, but otherwise this isn't really a fast64 issue.
Here is a link for ref: https://sites.google.com/view/supermario64romhacks/tweaks-and-tutorials?authuser=0
