### ISSUE TITLE
Improve combiner overflow behavior

### ISSUE THREAD

**Issue by Dragorn421** [Fast-64/fast64#348]
https://github.com/Fast-64/fast64/pull/335 (tried to) improve combiner overflow behavior

but we had to revert it due to breaking preview of other things https://github.com/Fast-64/fast64/pull/347

So that improvement is back on the table

**Comment by jesusyoshi54** [comment]
So basically the comber C input overflows >= 256, which is only on the 1.0 input, the others are 255 max. I didn't account for this the second time i edited the nodes woopsie.
Somehow I didn't see this when I tested because I only tested that the aberrant behavior was fixed not that all manner of normal behavior still worked.

**Comment by jesusyoshi54** [comment]
Can someone post some of the combiners of the broken materials shown in #347 I can't quite recreate the extent with which things get messed up.
