### ISSUE TITLE
I just wanna export to roblox. When i open template, doesnt work

### ISSUE THREAD

**Issue by SANTIQDCO** [Fast-64/fast64#473]
I cant even texture mario and bones work on blender but not studio so i need help : video soon, texture start blank and texture i cant add.

**Comment by Lilaa3** [comment]
Please think about what you are actually writing in an issue more. This isn't a plugin targeting roblox users; it's an N64 exporter. No one here is required to know the roblox workflow. So if you come on here and just tell us "you exported to roblox" that has very little information for a bunch of n64 devs.
That said I do know that roblox relies on .obj imports (which you should have mentioned). Blender is not capable of interpreting fast64's complex shader node tree used to emulate n64 visuals accurately. This is a known issue and it can only be fixed by the individual exporter devs or by specific hacks like implemented in #368 for glTF. I plan to pr a new f3d to bsdf converter (requested by a member of the community previously) next week which you should be able to use to get back basic bsdf materials that work well for the glTF and obj exporter (main feature set I'm targeting), currently having some personal issues so don´t expect it by monday.
Thank you for trying to report it, I'll close this for now!

**Comment by SonicTheHedgeHog64** [comment]
sounds like a whole buncha stupidity
